macromolecule(a).
macromolecule(b).
complex(c).
subMacromolecule(e).
subComplex(d).
subMacromolecule(f).
component(e,c,1).
component(d,c,1).
component(f,d,1).
process(p).
reactant(a,p).
product(b,p).
stimulates(c,p).
label(a,"A").
label(b,"β").
label(e,"E").
label(f,"F").
process(q).
macromolecule(g).
label(g,"G").
reactant(g,q,1).
product(a,q,1).
